### ISSUE TITLE
Choosenim doesn't install vccexe for use with Nimporter on Windows using MSVC

### ISSUE THREAD

**Issue by Pebaz** [juancarlospaco/choosenim_install#2]
For some reason, vccexe needed by Nimporter on Windows was not installed by Choosenim, but when I manually installed Nim, it was included. Any thoughts on why this would be and how to fix it?

**Comment by juancarlospaco** [comment]
I think it installs GCC instead, Nimporter should not assume MSVC is always installed, but try to detect MSVC or GCC.

**Comment by Pebaz** [comment]
Makes sense. Will update Nimporter to try to detect MSVC/GCC.
