### ISSUE TITLE
Choosenim doesn't install Nim standard library

### ISSUE THREAD

**Issue by Pebaz** [juancarlospaco/choosenim_install#3]
I grepped my hard disk looking for `system.nim` needed by Nimporter for any compilation, and none was found.

Unfortunately, without a way to solve this one, choosenim installation is not an option because Nimporter needs to find the standard library for source and binary distributions.

**Comment by Pebaz** [comment]
Info: Normally it should be in the `lib/system.nim` folder next to the `bin/` directory holding all the Nim binaries. For some reason, it's not there after I installed `choosenim_install`.

**Comment by Pebaz** [comment]
I think I found the solution. `choosenim_install` needs to copy/paste the `choosenim` binary somewhere onto the PATH so that Nimporter can use `choosenim` to find the standard library.

**Comment by Pebaz** [comment]
Perhaps it could install it into Python's `Scripts` directory on Win32 or `bin` on *nix.

**Comment by Pebaz** [comment]
More info: I believe I found a way to work with all 3 installation methods using Nimporter:
1. Choosenim
2. choosenim_install
3. Manual installation

But still testing. Will post results here.

**Comment by juancarlospaco** [comment]
https://github.com/nim-lang/Nim/search?q=findNimStdLibCompileTime

**Comment by Pebaz** [comment]
Found a way to work with all 3 installation methods.
