### ISSUE TITLE
choosenim version is old

### ISSUE THREAD

**Issue by develooper1994** [juancarlospaco/choosenim_install#9]
Can you update choosenim version?
The current version is choosenim_install-0.5.5.zip

**Comment by juancarlospaco** [comment]
It does not bundle any choosenim anymore in the code in master,
it has been completely rewritten, by copying choosenim behaviour, but using pure python code.

It has been tested in ARM, x86_64, x86_32, Windows and Linux.
We do not have Mac, but should work Ok there too.
Should work with any version of Python >= 3.5.0, tested with Python 3.10.0 too.

The way of bundling several choosenims was not stable and fails randomly for unknown reasons.
I hope this pure python Nim installer is better, Testers welcome...

**Comment by juancarlospaco** [comment]
Please use the version from git repo directly, it is fixed on git.
